---
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Research topic: Customer Purchases Behavior  

### Team members: Kaitlyn Hoyme and Christopher Moseley  

### Data:   



```{r, message=FALSE, warning=FALSE}
library(dplyr)
library(ggplot2)

#Data: description of your data set, first data cleaning steps, marginal summaries;

url <- "https://raw.githubusercontent.com/khoy24/DS202FinalProject/main/customer_data.csv"
data <- read.csv(url)
 
any(is.na(data))
# no missing entries

duplicateRows <- data %>% filter(duplicated(.))
print(nrow(duplicateRows))
#no duplicate rows



calculate_summary <- function(column) {
  c(
    mean = mean(column, na.rm = TRUE),
    median = median(column, na.rm = TRUE),
    sd = sd(column, na.rm = TRUE),
    min = min(column, na.rm = TRUE),
    max = max(column, na.rm = TRUE),
    range = diff(range(column, na.rm = TRUE))  # Range is the difference between max and min
  )
}

summary_stats <- data.frame(
  age = calculate_summary(data$age),
  income = calculate_summary(data$income),
  purchase_amount = calculate_summary(data$purchase_amount)
)

print(summary_stats)

```

  
### Questions to be addressed: 

- How does gender affect customer purchasing history
  
